# This file automatically generated by
#    /Users/jaredcasey/GIT/couchbase/clients/python/analytics-python-client/./couchbase_analytics_version.py
# at
#    2025-08-01 15:43:36.591881
__version__ = '0.0.1'
